-- Создать таблицу tableware, если она не существует
CREATE TABLE IF NOT EXISTS tableware (
    id SERIAL PRIMARY KEY,              -- Уникальный идентификатор
    name VARCHAR(255) NOT NULL,         -- Название посуды (уникальное и не может быть пустым)
    material VARCHAR(100) NOT NULL,     -- Материал (уникальное и не может быть пустым)
    type VARCHAR(50) NOT NULL,          -- Тип посуды (не может быть пустым)
    volume_ml INTEGER NOT NULL,         -- Объём в миллилитрах (не может быть пустым)
    price_rub INTEGER NOT NULL,         -- Цена в рублях (не может быть пустым)
    CONSTRAINT unique_name_material UNIQUE (name, material) -- Уникальное ограничение на сочетание name и material
);

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    status VARCHAR(10) CHECK (status IN ('ROLE_USER', 'ROLE_ADMIN'))
);

-- Вставить записи в таблицу
INSERT INTO tableware (name, material, type, volume_ml, price_rub)
VALUES
    ('Озеро', 'Керамика', 'Тарелка', 500, 300),
    ('Победитель', 'Фарфор', 'Кружка', 300, 150),
    ('Слава', 'Чугун', 'Сковорода', 2000, 1200),
    ('Богатырь', 'Алюминий', 'Кастрюля', 5000, 800),
    ('Балерина', 'Стекло', 'Кружка', 400, 250),
    ('Лебедь', 'Нержавеющая сталь', 'Чайник', 1500, 750),
    ('Молот', 'Дерево', 'Ложка', 40, 100),
    ('Салатница', 'Стекло', 'Тарелка', 1000, 350),
    ('Наковальня', 'Нержавеющая сталь', 'Ложка', 40, 60),
    ('Ловилка', 'Нержавеющая сталь', 'Вилка', 0, 50)
ON CONFLICT (name, material) DO NOTHING; -- Избежать дублирования записей